const countries = [
  { "label": "Afghanistan", "value": "AF" },
  { "label": "Åland Islands", "value": "AX" },
  { "label": "Albania", "value": "AL" },
  { "label": "Algeria", "value": "DZ" },
  { "label": "American Samoa", "value": "AS" },
  { "label": "Andorra", "value": "AD" },
  { "label": "Angola", "value": "AO" },
  { "label": "Anguilla", "value": "AI" },
  { "label": "Antarctica", "value": "AQ" },
  { "label": "Antigua and Barbuda", "value": "AG" },
  { "label": "Argentina", "value": "AR" },
  { "label": "Armenia", "value": "AM" },
  { "label": "Aruba", "value": "AW" },
  { "label": "Australia", "value": "AU" },
  { "label": "Austria", "value": "AT" },
  { "label": "Azerbaijan", "value": "AZ" },
  { "label": "Bahamas", "value": "BS" },
  { "label": "Bahrain", "value": "BH" },
  { "label": "Bangladesh", "value": "BD" },
  { "label": "Barbados", "value": "BB" },
  { "label": "Belarus", "value": "BY" },
  { "label": "Belgium", "value": "BE" },
  { "label": "Belize", "value": "BZ" },
  { "label": "Benin", "value": "BJ" },
  { "label": "Bermuda", "value": "BM" },
  { "label": "Bhutan", "value": "BT" },
  { "label": "Bolivia", "value": "BO" },
  { "label": "Bosnia and Herzegovina", "value": "BA" },
  { "label": "Botswana", "value": "BW" },
  { "label": "Bouvet Island", "value": "BV" },
  { "label": "Brazil", "value": "BR" },
  { "label": "British Indian Ocean Territory", "value": "IO" },
  { "label": "Brunei Darussalam", "value": "BN" },
  { "label": "Bulgaria", "value": "BG" },
  { "label": "Burkina Faso", "value": "BF" },
  { "label": "Burundi", "value": "BI" },
  { "label": "Cambodia", "value": "KH" },
  { "label": "Cameroon", "value": "CM" },
  { "label": "Canada", "value": "CA" },
  { "label": "Cape Verde", "value": "CV" },
  { "label": "Cayman Islands", "value": "KY" },
  { "label": "Central African Republic", "value": "CF" },
  { "label": "Chad", "value": "TD" },
  { "label": "Chile", "value": "CL" },
  { "label": "China", "value": "CN" },
  { "label": "Christmas Island", "value": "CX" },
  { "label": "Cocos (Keeling) Islands", "value": "CC" },
  { "label": "Colombia", "value": "CO" },
  { "label": "Comoros", "value": "KM" },
  { "label": "Congo", "value": "CG" },
  { "label": "Congo, The Democratic Republic of the", "value": "CD" },
  { "label": "Cook Islands", "value": "CK" },
  { "label": "Costa Rica", "value": "CR" },
  { "label": "Cote D'Ivoire", "value": "CI" },
  { "label": "Croatia", "value": "HR" },
  { "label": "Cuba", "value": "CU" },
  { "label": "Cyprus", "value": "CY" },
  { "label": "Czech Republic", "value": "CZ" },
  { "label": "Denmark", "value": "DK" },
  { "label": "Djibouti", "value": "DJ" },
  { "label": "Dominica", "value": "DM" },
  { "label": "Dominican Republic", "value": "DO" },
  { "label": "Ecuador", "value": "EC" },
  { "label": "Egypt", "value": "EG" },
  { "label": "El Salvador", "value": "SV" },
  { "label": "Equatorial Guinea", "value": "GQ" },
  { "label": "Eritrea", "value": "ER" },
  { "label": "Estonia", "value": "EE" },
  { "label": "Ethiopia", "value": "ET" },
  { "label": "Falkland Islands (Malvinas)", "value": "FK" },
  { "label": "Faroe Islands", "value": "FO" },
  { "label": "Fiji", "value": "FJ" },
  { "label": "Finland", "value": "FI" },
  { "label": "France", "value": "FR" },
  { "label": "French Guiana", "value": "GF" },
  { "label": "French Polynesia", "value": "PF" },
  { "label": "French Southern Territories", "value": "TF" },
  { "label": "Gabon", "value": "GA" },
  { "label": "Gambia", "value": "GM" },
  { "label": "Georgia", "value": "GE" },
  { "label": "Germany", "value": "DE" },
  { "label": "Ghana", "value": "GH" },
  { "label": "Gibraltar", "value": "GI" },
  { "label": "Greece", "value": "GR" },
  { "label": "Greenland", "value": "GL" },
  { "label": "Grenada", "value": "GD" },
  { "label": "Guadeloupe", "value": "GP" },
  { "label": "Guam", "value": "GU" },
  { "label": "Guatemala", "value": "GT" },
  { "label": "Guernsey", "value": "GG" },
  { "label": "Guinea", "value": "GN" },
  { "label": "Guinea-Bissau", "value": "GW" },
  { "label": "Guyana", "value": "GY" },
  { "label": "Haiti", "value": "HT" },
  { "label": "Heard Island and Mcdonald Islands", "value": "HM" },
  { "label": "Holy See (Vatican City State)", "value": "VA" },
  { "label": "Honduras", "value": "HN" },
  { "label": "Hong Kong", "value": "HK" },
  { "label": "Hungary", "value": "HU" },
  { "label": "Iceland", "value": "IS" },
  { "label": "India", "value": "IN" },
  { "label": "Indonesia", "value": "ID" },
  { "label": "Iran, Islamic Republic Of", "value": "IR" },
  { "label": "Iraq", "value": "IQ" },
  { "label": "Ireland", "value": "IE" },
  { "label": "Isle of Man", "value": "IM" },
  { "label": "Israel", "value": "IL" },
  { "label": "Italy", "value": "IT" },
  { "label": "Jamaica", "value": "JM" },
  { "label": "Japan", "value": "JP" },
  { "label": "Jersey", "value": "JE" },
  { "label": "Jordan", "value": "JO" },
  { "label": "Kazakhstan", "value": "KZ" },
  { "label": "Kenya", "value": "KE" },
  { "label": "Kiribati", "value": "KI" },
  { "label": "Korea, Democratic People's Republic of", "value": "KP" },
  { "label": "Korea, Republic of", "value": "KR" },
  { "label": "Kuwait", "value": "KW" },
  { "label": "Kyrgyzstan", "value": "KG" },
  { "label": "Lao People's Democratic Republic", "value": "LA" },
  { "label": "Latvia", "value": "LV" },
  { "label": "Lebanon", "value": "LB" },
  { "label": "Lesotho", "value": "LS" },
  { "label": "Liberia", "value": "LR" },
  { "label": "Libyan Arab Jamahiriya", "value": "LY" },
  { "label": "Liechtenstein", "value": "LI" },
  { "label": "Lithuania", "value": "LT" },
  { "label": "Luxembourg", "value": "LU" },
  { "label": "Macao", "value": "MO" },
  { "label": "Macedonia, The Former Yugoslav Republic of", "value": "MK" },
  { "label": "Madagascar", "value": "MG" },
  { "label": "Malawi", "value": "MW" },
  { "label": "Malaysia", "value": "MY" },
  { "label": "Maldives", "value": "MV" },
  { "label": "Mali", "value": "ML" },
  { "label": "Malta", "value": "MT" },
  { "label": "Marshall Islands", "value": "MH" },
  { "label": "Martinique", "value": "MQ" },
  { "label": "Mauritania", "value": "MR" },
  { "label": "Mauritius", "value": "MU" },
  { "label": "Mayotte", "value": "YT" },
  { "label": "Mexico", "value": "MX" },
  { "label": "Micronesia, Federated States of", "value": "FM" },
  { "label": "Moldova, Republic of", "value": "MD" },
  { "label": "Monaco", "value": "MC" },
  { "label": "Mongolia", "value": "MN" },
  { "label": "Montserrat", "value": "MS" },
  { "label": "Morocco", "value": "MA" },
  { "label": "Mozambique", "value": "MZ" },
  { "label": "Myanmar", "value": "MM" },
  { "label": "Namibia", "value": "NA" },
  { "label": "Nauru", "value": "NR" },
  { "label": "Nepal", "value": "NP" },
  { "label": "Netherlands", "value": "NL" },
  { "label": "Netherlands Antilles", "value": "AN" },
  { "label": "New Caledonia", "value": "NC" },
  { "label": "New Zealand", "value": "NZ" },
  { "label": "Nicaragua", "value": "NI" },
  { "label": "Niger", "value": "NE" },
  { "label": "Nigeria", "value": "NG" },
  { "label": "Niue", "value": "NU" },
  { "label": "Norfolk Island", "value": "NF" },
  { "label": "Northern Mariana Islands", "value": "MP" },
  { "label": "Norway", "value": "NO" },
  { "label": "Oman", "value": "OM" },
  { "label": "Pakistan", "value": "PK" },
  { "label": "Palau", "value": "PW" },
  { "label": "Palestinian Territory, Occupied", "value": "PS" },
  { "label": "Panama", "value": "PA" },
  { "label": "Papua New Guinea", "value": "PG" },
  { "label": "Paraguay", "value": "PY" },
  { "label": "Peru", "value": "PE" },
  { "label": "Philippines", "value": "PH" },
  { "label": "Pitcairn", "value": "PN" },
  { "label": "Poland", "value": "PL" },
  { "label": "Portugal", "value": "PT" },
  { "label": "Puerto Rico", "value": "PR" },
  { "label": "Qatar", "value": "QA" },
  { "label": "Reunion", "value": "RE" },
  { "label": "Romania", "value": "RO" },
  { "label": "Russian Federation", "value": "RU" },
  { "label": "Rwanda", "value": "RW" },
  { "label": "Saint Helena", "value": "SH" },
  { "label": "Saint Kitts and Nevis", "value": "KN" },
  { "label": "Saint Lucia", "value": "LC" },
  { "label": "Saint Pierre and Miquelon", "value": "PM" },
  { "label": "Saint Vincent and the Grenadines", "value": "VC" },
  { "label": "Samoa", "value": "WS" },
  { "label": "San Marino", "value": "SM" },
  { "label": "Sao Tome and Principe", "value": "ST" },
  { "label": "Saudi Arabia", "value": "SA" },
  { "label": "Senegal", "value": "SN" },
  { "label": "Serbia and Montenegro", "value": "CS" },
  { "label": "Seychelles", "value": "SC" },
  { "label": "Sierra Leone", "value": "SL" },
  { "label": "Singapore", "value": "SG" },
  { "label": "Slovakia", "value": "SK" },
  { "label": "Slovenia", "value": "SI" },
  { "label": "Solomon Islands", "value": "SB" },
  { "label": "Somalia", "value": "SO" },
  { "label": "South Africa", "value": "ZA" },
  { "label": "South Georgia and the South Sandwich Islands", "value": "GS" },
  { "label": "Spain", "value": "ES" },
  { "label": "Sri Lanka", "value": "LK" },
  { "label": "Sudan", "value": "SD" },
  { "label": "Suriname", "value": "SR" },
  { "label": "Svalbard and Jan Mayen", "value": "SJ" },
  { "label": "Swaziland", "value": "SZ" },
  { "label": "Sweden", "value": "SE" },
  { "label": "Switzerland", "value": "CH" },
  { "label": "Syrian Arab Republic", "value": "SY" },
  { "label": "Taiwan, Province of China", "value": "TW" },
  { "label": "Tajikistan", "value": "TJ" },
  { "label": "Tanzania, United Republic of", "value": "TZ" },
  { "label": "Thailand", "value": "TH" },
  { "label": "Timor-Leste", "value": "TL" },
  { "label": "Togo", "value": "TG" },
  { "label": "Tokelau", "value": "TK" },
  { "label": "Tonga", "value": "TO" },
  { "label": "Trinidad and Tobago", "value": "TT" },
  { "label": "Tunisia", "value": "TN" },
  { "label": "Turkey", "value": "TR" },
  { "label": "Turkmenistan", "value": "TM" },
  { "label": "Turks and Caicos Islands", "value": "TC" },
  { "label": "Tuvalu", "value": "TV" },
  { "label": "Uganda", "value": "UG" },
  { "label": "Ukraine", "value": "UA" },
  { "label": "United Arab Emirates", "value": "AE" },
  { "label": "United Kingdom", "value": "GB" },
  { "label": "United States", "value": "US" },
  { "label": "United States Minor Outlying Islands", "value": "UM" },
  { "label": "Uruguay", "value": "UY" },
  { "label": "Uzbekistan", "value": "UZ" },
  { "label": "Vanuatu", "value": "VU" },
  { "label": "Venezuela", "value": "VE" },
  { "label": "Viet Nam", "value": "VN" },
  { "label": "Virgin Islands, British", "value": "VG" },
  { "label": "Virgin Islands, U.S.", "value": "VI" },
  { "label": "Wallis and Futuna", "value": "WF" },
  { "label": "Western Sahara", "value": "EH" },
  { "label": "Yemen", "value": "YE" },
  { "label": "Zambia", "value": "ZM" },
  { "label": "Zimbabwe", "value": "ZW" }
];

const currencies = [
  { code: "AED", label: "United Arab Emirates dirham", value: "AED" },
  { code: "AFN", label: "Afghan afghani", symbol: "؋", value: "AFN" },
  { code: "ALL", label: "Albanian lek", value: "ALL" },
  { code: "AMD", label: "Armenian dram", symbol: "֏", value: "AMD" },
  {
    code: "ANG",
    label: "Netherlands Antillean guilder",
    symbol: "ƒ",
    value: "ANG",
  },
  { code: "AOA", label: "Angolan kwanza", value: "AOA" },
  { code: "ARS", label: "Argentine peso", symbol: "$", value: "ARS" },
  { code: "AUD", label: "Australian dollar", symbol: "$", value: "AUD" },
  { code: "AWG", label: "Aruban florin", symbol: "ƒ", value: "AWG" },
  { code: "AZN", label: "Azerbaijani manat", symbol: "₼", value: "AZN" },
  {
    code: "BAM",
    label: "Bosnia and Herzegovina convertible mark",
    symbol: "KM",
    value: "BAM",
  },
  { code: "BBD", label: "Barbadian dollar", symbol: "$", value: "BBD" },
  { code: "BDT", label: "Bangladeshi taka", symbol: "৳", value: "BDT" },
  { code: "BGN", label: "Bulgarian lev", symbol: "лв", value: "BGN" },
  { code: "BHD", label: "Bahraini dinar", value: "BHD" },
  { code: "BIF", label: "Burundian franc", value: "BIF" },
  { code: "BMD", label: "Bermudian dollar", symbol: "$", value: "BMD" },
  { code: "BND", label: "Brunei dollar", symbol: "$", value: "BND" },
  { code: "BOB", label: "Boliviano", symbol: "Bs.", value: "BOB" },
  { code: "BRL", label: "Brazilian real", symbol: "R$", value: "BRL" },
  { code: "BSD", label: "Bahamian dollar", symbol: "$", value: "BSD" },
  { code: "BTN", label: "Bhutanese ngultrum", symbol: "Nu.", value: "BTN" },
  { code: "BWP", label: "Botswana pula", symbol: "P", value: "BWP" },
  { code: "BYN", label: "Belarusian ruble", value: "BYN" },
  { code: "BZD", label: "Belize dollar", symbol: "BZ$", value: "BZD" },
  { code: "CAD", label: "Canadian dollar", symbol: "$", value: "CAD" },
  { code: "CDF", label: "Congolese franc", value: "CDF" },
  { code: "CHF", label: "Swiss franc", symbol: "CHF", value: "CHF" },
  { code: "CLP", label: "Chilean peso", symbol: "$", value: "CLP" },
  { code: "CNY", label: "Chinese yuan", symbol: "¥", value: "CNY" },
  { code: "COP", label: "Colombian peso", symbol: "$", value: "COP" },
  { code: "CRC", label: "Costa Rican colón", symbol: "₡", value: "CRC" },
  { code: "CUP", label: "Cuban peso", symbol: "$", value: "CUP" },
  { code: "CVE", label: "Cape Verdean escudo", value: "CVE" },
  { code: "CZK", label: "Czech koruna", symbol: "Kč", value: "CZK" },
  { code: "DJF", label: "Djiboutian franc", value: "DJF" },
  { code: "DKK", label: "Danish krone", symbol: "kr", value: "DKK" },
  { code: "DOP", label: "Dominican peso", symbol: "RD$", value: "DOP" },
  { code: "DZD", label: "Algerian dinar", value: "DZD" },
  { code: "EGP", label: "Egyptian pound", symbol: "£", value: "EGP" },
  { code: "ERN", label: "Eritrean nakfa", value: "ERN" },
  { code: "ETB", label: "Ethiopian birr", symbol: "Br", value: "ETB" },
  { code: "EUR", label: "Euro", symbol: "€", value: "EUR" },
  { code: "FJD", label: "Fijian dollar", symbol: "$", value: "FJD" },
  { code: "FKP", label: "Falkland Islands pound", symbol: "£", value: "FKP" },
  { code: "GBP", label: "British pound", symbol: "£", value: "GBP" },
  { code: "GEL", label: "Georgian lari", symbol: "₾", value: "GEL" },
  { code: "GHS", label: "Ghanaian cedi", symbol: "₵", value: "GHS" },
  { code: "GIP", label: "Gibraltar pound", symbol: "£", value: "GIP" },
  { code: "GMD", label: "Gambian dalasi", symbol: "D", value: "GMD" },
  { code: "GNF", label: "Guinean franc", symbol: "Fr", value: "GNF" },
  { code: "GTQ", label: "Guatemalan quetzal", symbol: "Q", value: "GTQ" },
  { code: "GYD", label: "Guyanese dollar", symbol: "$", value: "GYD" },
  { code: "HKD", label: "Hong Kong dollar", symbol: "$", value: "HKD" },
  { code: "HNL", label: "Honduran lempira", symbol: "L", value: "HNL" },
  { code: "HRK", label: "Croatian kuna", symbol: "kn", value: "HRK" },
  { code: "HTG", label: "Haitian gourde", symbol: "G", value: "HTG" },
  { code: "HUF", label: "Hungarian forint", symbol: "Ft", value: "HUF" },
  { code: "IDR", label: "Indonesian rupiah", symbol: "Rp", value: "IDR" },
  { code: "ILS", label: "Israeli new shekel", symbol: "₪", value: "ILS" },
  { code: "INR", label: "Indian rupee", symbol: "₹", value: "INR" },
  { code: "IQD", label: "Iraqi dinar", symbol: "ع.د", value: "IQD" },
  { code: "IRR", label: "Iranian rial", symbol: "﷼", value: "IRR" },
  { code: "ISK", label: "Icelandic króna", symbol: "kr", value: "ISK" },
  { code: "JMD", label: "Jamaican dollar", symbol: "J$", value: "JMD" },
  { code: "JOD", label: "Jordanian dinar", symbol: "د.ا", value: "JOD" },
  { code: "JPY", label: "Japanese yen", symbol: "¥", value: "JPY" },
  { code: "KES", label: "Kenyan shilling", symbol: "KSh", value: "KES" },
  { code: "KGS", label: "Kyrgyzstani som", symbol: "сом", value: "KGS" },
  { code: "KHR", label: "Cambodian riel", symbol: "៛", value: "KHR" },
  { code: "KMF", label: "Comorian franc", value: "KMF" },
  { code: "KPW", label: "North Korean won", symbol: "₩", value: "KPW" },
  { code: "KRW", label: "South Korean won", symbol: "₩", value: "KRW" },
  { code: "KWD", label: "Kuwaiti dinar", symbol: "د.ك", value: "KWD" },
  { code: "KYD", label: "Cayman Islands dollar", symbol: "$", value: "KYD" },
  { code: "KZT", label: "Kazakhstani tenge", symbol: "₸", value: "KZT" },
  { code: "LAK", label: "Lao kip", symbol: "₭", value: "LAK" },
  { code: "LBP", label: "Lebanese pound", symbol: "ل.ل", value: "LBP" },
  { code: "LKR", label: "Sri Lankan rupee", symbol: "Rs", value: "LKR" },
  { code: "LSL", label: "Lesotho loti", value: "LSL" },
  { code: "LYD", label: "Libyan dinar", value: "LYD" },
  { code: "MAD", label: "Moroccan dirham", symbol: "د.م.", value: "MAD" },
  { code: "MDL", label: "Moldovan leu", symbol: "L", value: "MDL" },
  { code: "MGA", label: "Malagasy ariary", symbol: "Ar", value: "MGA" },
  { code: "MKD", label: "Macedonian denar", symbol: "ден", value: "MKD" },
  { code: "MMK", label: "Myanma kyat", symbol: "Ks", value: "MMK" },
  { code: "MNT", label: "Mongolian tögrög", symbol: "₮", value: "MNT" },
  { code: "MOP", label: "Macanese pataca", symbol: "MOP$", value: "MOP" },
  { code: "MRU", label: "Mauritanian ouguiya", symbol: "UM", value: "MRU" },
  { code: "MUR", label: "Mauritian rupee", symbol: "₨", value: "MUR" },
  { code: "MVR", label: "Maldivian rufiyaa", symbol: "ރ.", value: "MVR" },
  { code: "MWK", label: "Malawian kwacha", symbol: "MK", value: "MWK" },
  { code: "MXN", label: "Mexican peso", symbol: "Mex$", value: "MXN" },
  { code: "MYR", label: "Malaysian ringgit", symbol: "RM", value: "MYR" },
  { code: "MZN", label: "Mozambican metical", symbol: "MTn", value: "MZN" },
  { code: "NAD", label: "Namibian dollar", symbol: "$", value: "NAD" },
  { code: "NGN", label: "Nigerian naira", symbol: "₦", value: "NGN" },
  { code: "NIO", label: "Nicaraguan córdoba", symbol: "C$", value: "NIO" },
  { code: "NOK", label: "Norwegian krone", symbol: "kr", value: "NOK" },
  { code: "NPR", label: "Nepalese rupee", symbol: "Rs", value: "NPR" },
  { code: "NZD", label: "New Zealand dollar", symbol: "$", value: "NZD" },
];

export { countries, currencies };
