export enum FILTER_FUNCTIONS_ENUM {
  CONTAINS = "contains",
  STARTS_WITH = "startsWith",
  ENDS_WITH = "endsWith",
  EQUALS = "equals",
  NOT_EQUAL = "notEqual",
  GREATER_THAN = "greaterThan",
  GREATER_THAN_OR_EQUAL = "greaterThanOrEqual",
  LESS_THAN = "lessThan",
  LESS_THAN_OR_EQUAL = "lessThanOrEqual",
  IS_NULL = "isNull",
  IS_NOT_NULL = "isNotNull",
  IS_EMPTY = "isEmpty",
  IS_NOT_EMPTY = "isNotEmpty",
  LIKE = "like",
  NOT_LIKE = "notLike",
  IN = "in",
  NOT_IN = "notIn",
  BETWEEN = "between",
  NOT_BETWEEN = "notBetween",
}

export enum FILTER_OPERATORS_ENUM {
  CONTAINS = "ct",
  STARTS_WITH = "sw",
  ENDS_WITH = "ew",
  EQUALS = "eq",
  GREATER_THAN = "gt",
  GREATER_THAN_OR_EQUAL = "gte",
  LESS_THAN = "lt",
  LESS_THAN_OR_EQUAL = "lte",
  NULL = "null",
  EMPTY = "empty",
  LIKE = "like",
  IN = "in",
  BETWEEN = "bt",
}
