const city = [
  { label: "Atlanta", value: "Atlanta" },
  { label: "Austin", value: "Austin" },
  { label: "Boston", value: "Boston" },
  { label: "Charlotte", value: "Charlotte" },
  { label: "Chicago", value: "Chicago" },
  { label: "Dallas-Fort Worth", value: "Dallas-Fort Worth" },
  { label: "Denver", value: "Denver" },
  { label: "Detroit", value: "Detroit" },
  { label: "Houston", value: "Houston" },
  { label: "Los Angeles", value: "Los Angeles" },
  { label: "Miami Beach", value: "Miami Beach" },
  { label: "Minneapolis", value: "Minneapolis" },
  { label: "Nashville", value: "Nashville" },
  { label: "New York", value: "New York" },
  { label: "Philadelphia", value: "Philadelphia" },
  { label: "Phoenix", value: "Phoenix" },
  { label: "Portland", value: "Portland" },
  { label: "San Diego", value: "San Diego" },
  { label: "San Francisco Bay Area", value: "San Francisco Bay Area" },
  { label: "Seattle", value: "Seattle" },
];

const data = [
  {
    age: 28,
    city: "New York",
    email: "john.doe@example.com",
    id: 1,
    name: "John Doe",
  },
  {
    age: 32,
    city: "Los Angeles",
    email: "jane.smith@example.com",
    id: 2,
    name: "Jane Elizabeth Smith",
  },
  {
    age: 25,
    city: "Chicago",
    email: "bob.j@example.com",
    id: 3,
    name: "Robert Johnson",
  },
  {
    age: 22,
    city: "San Francisco Bay Area",
    email: "alice.brown@example.com",
    id: 4,
    name: "Alice Brown",
  },
  {
    age: 35,
    city: "Houston",
    email: "charlie.w@example.com",
    id: 5,
    name: "Charles William Wilson Jr.",
  },
  {
    age: 30,
    city: "Miami Beach",
    email: "eva.martinez@example.com",
    id: 6,
    name: "Evangeline Martinez",
  },
  {
    age: 27,
    city: "Seattle",
    email: "david.lee@example.com",
    id: 7,
    name: "David Lawrence",
  },
  {
    age: 29,
    city: "Atlanta",
    email: "sophie.t@example.com",
    id: 8,
    name: "Sophia Turner",
  },
  {
    age: 31,
    city: "Dallas-Fort Worth",
    email: "michael.a@example.com",
    id: 9,
    name: "Michael Anthony Adams",
  },
  {
    age: 26,
    city: "Denver",
    email: "olivia.carter@example.com",
    id: 10,
    name: "Olivia Charlotte Carter",
  },
  {
    age: 34,
    city: "Boston",
    disabled: true,
    email: "ryan.cooper@example.com",
    id: 11,
    name: "Ryan Alexander Cooper",
  },
  {
    age: 33,
    city: "Phoenix",
    disabled: true,
    email: "emily.d@example.com",
    id: 12,
    name: "Emily Davis",
  },
  {
    age: 28,
    city: "Philadelphia",
    disabled: true,
    email: "daniel.white@example.com",
    id: 13,
    name: "Daniel William White",
  },
  {
    age: 24,
    city: "Austin",
    disabled: false,
    email: "ava.m@example.com",
    id: 14,
    name: "Ava Rose Moore",
  },
  {
    age: 27,
    city: "San Diego",
    disabled: false,
    email: "nicholas.h@example.com",
    id: 15,
    name: "Nicholas Harrison",
  },
  {
    age: 29,
    city: "Portland",
    email: "emma.t@example.com",
    id: 16,
    name: "Emma Grace Turner",
  },
  {
    age: 32,
    city: "Detroit",
    email: "william.l@example.com",
    id: 17,
    name: "William Lewis Jr.",
  },
  {
    age: 26,
    city: "Minneapolis",
    email: "grace.murphy@example.com",
    id: 18,
    name: "Grace Margaret Murphy",
  },
  {
    age: 30,
    city: "Charlotte",
    email: "matthew.w@example.com",
    id: 19,
    name: "Matthew Wright",
  },
  {
    age: 31,
    city: "Nashville",
    email: "lily.adams@example.com",
    id: 20,
    name: "Lily Alexandra Adams",
  },
];

const formatDemoData = [
  {
    amount: 1_234_567.89,
    date: null,
    datetime: null,
    description: "Purchase of equipment",
    id: 1001,
    quantity: 420,
  },
  {
    amount: 987_654.32,
    date: new Date("2023-12-01T12:30:00"),
    datetime: new Date("2023-12-01T11:00:00"),
    description: "Office rent payment",
    id: 1002,
    quantity: 175,
  },
  {
    amount: 54321,
    date: new Date("2023-12-15T08:45:00"),
    datetime: new Date("2023-12-15T08:45:00"),
    description: "Marketing campaign expenses",
    id: 1003,
    quantity: 7890,
  },
  {
    amount: 654_321.12,
    date: new Date(),
    datetime: new Date(),
    description: "Product development costs",
    id: 1004,
    quantity: 2950,
  },
  {
    amount: 789_012.34,
    date: new Date("2023-12-05T09:15:00"),
    datetime: new Date("2023-12-05T09:15:00"),
    description: "Travel and accommodation",
    id: 1005,
    quantity: 53210,
  },
  {
    amount: 12345.67,
    date: new Date("2023-12-20T14:00:00"),
    datetime: new Date("2023-12-05T09:15:00"),
    description: "Employee salaries",
    id: 1006,
    quantity: 6430,
  },
  {
    amount: 234_567.89,
    date: new Date(),
    datetime: new Date(),
    description: "Product inventory replenishment",
    id: 1007,
    quantity: 98760,
  },
  {
    amount: 876_543.21,
    date: new Date("2023-12-10T18:45:00"),
    datetime: new Date("2023-12-10T18:45:00"),
    description: "New marketing materials",
    id: 1008,
    quantity: 123_450,
  },
  {
    amount: 13579.24,
    date: new Date("2023-12-25T11:30:00"),
    datetime: new Date("2023-12-25T11:30:00"),
    description: "Holiday season promotions",
    id: 1009,
    quantity: 45670,
  },
  {
    amount: 24680.36,
    date: new Date(),
    datetime: new Date(),
    description: "Office furniture upgrade",
    id: 1010,
    quantity: 78901,
  },
];

const invitations = [
  {
    acceptedAt: null,
    appId: 1,
    createdAt: new Date("2024-01-05").getTime(),
    email: "bob@dzangolab.com",
    expiresAt: new Date("2024-02-04").getTime(),
    id: 456,
    invitedBy: {
      disabled: false,
      email: "charlie@dzangolab.com",
      givenName: "Charlie",
      id: "user-4",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Brown",
      username: "charlieb",
    },
    invitedById: "user-4",
    payload: null,
    revokedAt: new Date("2024-01-14").getTime(),
    role: "USER",
    updatedAt: new Date("2024-01-14").getTime(),
  },
  {
    acceptedAt: null,
    appId: 1,
    createdAt: new Date("2024-01-05").getTime(),
    email: "jane@dzangolab.com",
    expiresAt: new Date("2024-02-04").getTime(),
    givenName: "Jane",
    id: 123,
    invitedBy: {
      disabled: false,
      email: "admin@dzangolab.com",
      givenName: "Admin",
      id: "user-2",
      isActiveUser: true,
      roles: ["USER"],
      surname: "User",
      username: "admin",
    },
    invitedById: "user-2",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: new Date("2024-02-24").getTime(),
    appId: 2,
    createdAt: new Date("2024-01-05").getTime(),
    email: "june@dzangolab.com",
    expiresAt: Date.now() + 4 * 24 * 60 * 60 * 1000,
    id: 789,
    invitedBy: {
      disabled: true,
      email: "jonny@dzangolab.com",
      givenName: "jonny",
      id: "user-8",
      isActiveUser: true,
      roles: ["USER"],
      surname: "smith",
      username: "admin",
    },
    invitedById: "user-8",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-05").getTime(),
    email: "janet@dzangolab.com",
    expiresAt: Date.now() + 4 * 24 * 60 * 60 * 1000,
    id: 789,
    invitedBy: {
      disabled: true,
      email: "jolly@dzangolab.com",
      givenName: "jolly",
      id: "user-8",
      isActiveUser: true,
      roles: ["USER"],
      surname: "doe",
      username: "admin",
    },
    invitedById: "user-8",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: null,
    appId: 1,
    createdAt: new Date("2024-01-10").getTime(),
    email: "alexander.smith1234@dzangolab.com",
    expiresAt: Date.now() + 4 * 24 * 60 * 60 * 1000,
    id: 890,
    invitedBy: {
      disabled: true,
      email: "michelle.williams@dzangolab.com",
      givenName: "Michelle Alexandra",
      id: "user-15",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Williams-Smithson",
      username: "admin",
    },
    invitedById: "user-15",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-01-24").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-03-01").getTime(),
    email: "george.harrison@dzangolab.com",
    expiresAt: new Date("2024-05-01").getTime(),
    id: 891,
    invitedBy: {
      disabled: false,
      email: "robert.johnson@dzangolab.com",
      givenName: "Robert James",
      id: "user-22",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Johnson-Longstreet",
      username: "moderator_robert",
    },
    invitedById: "user-22",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-03-03").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-15").getTime(),
    email: "lucas.martins@dzangolab.com",
    expiresAt: new Date("2024-03-15").getTime(),
    id: 892,
    invitedBy: {
      disabled: true,
      email: "david.jones@dzangolab.com",
      givenName: "David William",
      id: "user-34",
      isActiveUser: true,
      roles: ["ADMIN", "MODERATOR"],
      surname: "Jones-Smith",
      username: "admin_david_jones",
    },
    invitedById: "user-34",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-01-18").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-02-18").getTime(),
    email: "olivia.clark@dzangolab.com",
    expiresAt: new Date("2024-04-20").getTime(),
    id: 893,
    invitedBy: {
      disabled: false,
      email: "luke.martin@dzangolab.com",
      givenName: "Luke Robert",
      id: "user-18",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Martin",
      username: "user_luke",
    },
    invitedById: "user-18",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-21").getTime(),
  },
  {
    acceptedAt: null,
    appId: 4,
    createdAt: new Date("2024-03-05").getTime(),
    email: "jackson.davis@dzangolab.com",
    expiresAt: new Date("2024-05-05").getTime(),
    id: 894,
    invitedBy: {
      disabled: false,
      email: "emma.white@dzangolab.com",
      givenName: "Emma Nicole",
      id: "user-27",
      isActiveUser: true,
      roles: ["ADMIN", "MODERATOR"],
      surname: "White",
      username: "superadmin_emma",
    },
    invitedById: "user-27",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-03-07").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-02-05").getTime(),
    email: "sophia.brown@dzangolab.com",
    expiresAt: new Date("2024-04-06").getTime(),
    id: 895,
    invitedBy: {
      disabled: false,
      email: "michael.green@dzangolab.com",
      givenName: "Michael Christopher",
      id: "user-10",
      isActiveUser: true,
      roles: ["ADMIN", "USER"],
      surname: "Green",
      username: "admin_michael",
    },
    invitedById: "user-10",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-12").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-01-28").getTime(),
    email: "madeline.james@dzangolab.com",
    expiresAt: new Date("2024-03-28").getTime(),
    id: 896,
    invitedBy: {
      disabled: true,
      email: "brandon.kelly@dzangolab.org",
      givenName: "Brandon Nathaniel",
      id: "user-20",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Kelly",
      username: "admin_bkelly",
    },
    invitedById: "user-20",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-01").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-03-10").getTime(),
    email: "ethan.miller@dzangolab.com",
    expiresAt: new Date("2024-05-10").getTime(),
    id: 897,
    invitedBy: {
      disabled: false,
      email: "hannah.morris@dzangolab.com",
      givenName: "Hannah",
      id: "user-5",
      isActiveUser: true,
      roles: ["ADMIN"],
      surname: "Morris",
      username: "admin_hannah",
    },
    invitedById: "user-5",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-03-12").getTime(),
  },
  {
    acceptedAt: null,
    appId: 2,
    createdAt: new Date("2024-02-25").getTime(),
    email: "benjamin.martinez@dzangolab.com",
    expiresAt: new Date("2024-04-25").getTime(),
    id: 898,
    invitedBy: {
      disabled: false,
      email: "lucy.rodriguez@dzangolab.net",
      givenName: "Lucy Isabella",
      id: "user-12",
      isActiveUser: true,
      roles: ["ADMIN"],
      surname: "Rodriguez",
      username: "superadmin_lucy",
    },
    invitedById: "user-12",
    payload: null,
    revokedAt: null,
    role: "ADMIN",
    updatedAt: new Date("2024-02-28").getTime(),
  },
  {
    acceptedAt: null,
    appId: 3,
    createdAt: new Date("2024-01-30").getTime(),
    email: "claire.morgan@dzangolab.com",
    expiresAt: new Date("2024-03-30").getTime(),
    id: 899,
    invitedBy: {
      disabled: false,
      email: "jacob.smith@dzangolab.com",
      givenName: "Jacob",
      id: "user-16",
      isActiveUser: true,
      roles: ["USER"],
      surname: "Smith",
      username: "user_jacobsmith",
    },
    invitedById: "user-16",
    payload: null,
    revokedAt: null,
    role: "USER",
    updatedAt: new Date("2024-02-02").getTime(),
  },
];

export { city, data, formatDemoData, invitations };
