export const allUsers = [
  {
    disabled: false,
    email: "john@dzangolab.com",
    givenName: "John",
    id: "user-1",
    invitedBy: null,
    isActiveUser: true,
    lastLoginAt: 0,
    middleNames: null,
    name: "John Doe",
    roles: ["USER"],
    signedUpAt: new Date("2023-08-10T08:00:00Z").getTime(),
    surname: "Doe",
    timeJoined: 0,
    username: "johndoe",
  },
  {
    disabled: true,
    email: "jane@dzangolab.com",
    givenName: "Jane",
    id: "invitation-123",
    invitedBy: {
      email: "admin@dzangolab.com",
      givenName: "Admin",
      id: "user-2",
      isActiveUser: true,
      lastLoginAt: 0,
      middleNames: null,
      name: "Admin User",
      roles: ["USER"],
      signedUpAt: 0,
      surname: "User",
      timeJoined: 0,
      username: "admin",
    },
    isActiveUser: false,
    lastLoginAt: 0,
    middleNames: null,
    name: "Jane Smith",
    roles: ["ADMIN"],
    signedUpAt: 0,
    surname: "Smith",
    timeJoined: 0,
    username: "janesmith",
  },
  {
    disabled: false,
    email: "alice@dzangolab.com",
    givenName: "Alice",
    id: "user-3",
    invitedBy: null,
    isActiveUser: true,
    lastLoginAt: 0,
    middleNames: null,
    name: "Alice Johnson",
    roles: ["USER"],
    signedUpAt: new Date("2023-08-08T10:30:00Z").getTime(),
    surname: "Johnson",
    timeJoined: 0,
    username: "alicej",
  },
  {
    disabled: false,
    email: "bob@dzangolab.com",
    givenName: "Bob",
    id: "invitation-456",
    invitedBy: {
      email: "charlie@dzangolab.com",
      givenName: "Charlie",
      id: "user-4",
      isActiveUser: true,
      lastLoginAt: 0,
      middleNames: null,
      name: "Charlie Brown",
      roles: ["USER"],
      signedUpAt: 0,
      surname: "Brown",
      timeJoined: 0,
      username: "charlieb",
    },
    isActiveUser: false,
    lastLoginAt: 0,
    middleNames: null,
    name: "Bob Williams",
    roles: ["ADMIN"],
    signedUpAt: 0,
    surname: "Williams",
    timeJoined: 0,
    username: "bobw",
  },
  {
    disabled: true,
    email: "george@dzangolab.com",
    givenName: "george",
    id: "user-6",
    invitedBy: null,
    isActiveUser: true,
    lastLoginAt: 0,
    middleNames: null,
    name: "george williams",
    roles: ["USER"],
    signedUpAt: new Date("2023-10-10T08:00:00Z").getTime(),
    surname: "williams",
    timeJoined: 0,
    username: "george",
  },
];

export const apps = [
  {
    id: 1,
    name: "app-vue",
    origin: "app-vue-origin",
    supportedRoles: [
      {
        id: 1,
        name: "USER",
      },
    ],
  },
  {
    id: 2,
    name: "app-react",
    origin: "app-react-origin",
    supportedRoles: [
      {
        id: 1,
        name: "USER",
      },
    ],
  },
  {
    id: 3,
    name: "admin-react",
    origin: "admin-react-origin",
    supportedRoles: [
      {
        id: 2,
        name: "ADMIN",
      },
      {
        id: 3,
        name: "SUPERADMIN",
      },
    ],
  },
  {
    id: 4,
    name: "admin-vue",
    origin: "admin-vue-origin",
    supportedRoles: [
      {
        id: 2,
        name: "ADMIN",
      },
      {
        id: 3,
        name: "SUPERADMIN",
      },
    ],
  },
];
